services:
  products:
    build: ./services/products
    container_name: products_service
    ports:
      - "5001:5001"
    environment:
      - DB_HOST=products_db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=products_db
    depends_on:
      - products_db

  products_db:
    image: mysql:8.0
    container_name: products_db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=products_db
    volumes:
      - products_data:/var/lib/mysql

  clients:
    build: ./services/clients
    container_name: clients_service
    ports:
      - "5002:5002"
    environment:
      - DB_HOST=clients_db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=clients_db
    depends_on:
      - clients_db

  clients_db:
    image: mysql:8.0
    container_name: clients_db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=clients_db
    volumes:
      - clients_data:/var/lib/mysql

  sales:
    build: ./services/sales
    container_name: sales_service
    ports:
      - "5003:5003"
    environment:
      - MONGO_HOST=sales_db
      - MONGO_PORT=27017
    depends_on:
      - sales_db

  sales_db:
    image: mongo:6.0
    container_name: sales_db
    volumes:
      - sales_data:/data/db

  frontend:
    build: ./frontend
    container_name: frontend_service
    ports:
      - "3000:3000"
    depends_on:
      - products
      - clients
      - sales

volumes:
  products_data:
  clients_data:
  sales_data: